### ISSUE TITLE
Error When Executing Step "Make" in QT 6.1.1 (Windows 10)

### ISSUE THREAD

**Issue by GALATIYA** [groops-devs/groops#11]
Hi,

Thanks for the powerful tool: GROOPS

I am having challenges when I try to build GROOPS on windows 10 using QT 6.1.1. Would you please refer to lines
11, 65, and 85 in the attached text file.
[building_groops.txt](https://github.com/groops-devs/groops/files/6719196/building_groops.txt)

Thanks with kind regards.

Galatiya

**Comment by sestras** [comment]
Hello,

as stated in the installation guide, the GROOPS GUI is tested with Qt version 5.15.1. Qt 6 is a relatively recent release and not yet widely available on major platforms and distributions. Thus, we have not looked into the changes they made and have not tested it at all.

Since you are using Windows, you can just install the GUI from the precompiled Windows binaries that are provided with each release.

Best regards,
Sebastian
