### ISSUE TITLE
Example xml configuration file for GPS precise orbit determination

### ISSUE THREAD

**Issue by liudaweng** [groops-devs/groops#15]
Dear Developer,

Would you please be so kind as to provide  an example configuration file for GPS precise orbit determination, as done in the IGS orbits product processing ?  The example configuration xml file would be very helpful to the geodesy community. Would you please give the specific steps on the final orbit integration and prediction for the final orbit products. Many thanks !

Looking forward to your reply.

Kind Regards,
Daweng

**Comment by sestras** [comment]
Hello,

Release [2021-09-06](https://github.com/groops-devs/groops/releases/tag/2021-09-06) features a redesign of the GNSS processing interface to make usage a little bit easier and more flexible. In addition, we now provide GNSS [example scenarios](https://ftp.tugraz.at/outgoing/ITSG/groops/scenario/) with config files and data. Since the structure of the [GNSS-related GROOPS data and metadata](https://ftp.tugraz.at/outgoing/ITSG/groops/data/gnss/) has changed, we recommend to download the latest version. More information can be found in the updated [cookbooks and documentation](https://groops-devs.github.io/groops/html/index.html).

One of the example scenarios mentioned above (scenarioGnssNetwork) is GNSS orbit determination, so hopefully this helps.
