### ISSUE TITLE
GPS orbit prediction

### ISSUE THREAD

**Issue by liudaweng** [groops-devs/groops#16]
Hello Developers,  how can I get the predicted accurate GPS orbit (e.g.,  48-hour, cm-dm-level accuracy) after using 'PreprocessingVariationalEquation' and 'PreprocessingVariationalEquationOrbitFit' to fit IGS final orbits (24-hour) and get the estimated solar radiation pressure parameters ?  After the IGS orbit fitting, we only have the 24-hour fitted orbit. Could you give the xml configuration file for this kind of GPS orbit prediction? Looking forward to your reply. Many thanks !

**Comment by sestras** [comment]
Hello,

Release [2021-09-06](https://github.com/groops-devs/groops/releases/tag/2021-09-06) features a redesign of the GNSS processing interface to make usage a little bit easier and more flexible. In addition, we now provide GNSS [example scenarios](https://ftp.tugraz.at/outgoing/ITSG/groops/scenario/) with config files and data. Since the structure of the [GNSS-related GROOPS data and metadata](https://ftp.tugraz.at/outgoing/ITSG/groops/data/gnss/) has changed, we recommend to download the latest version. More information can be found in the updated [cookbooks and documentation](https://groops-devs.github.io/groops/html/index.html).

If you want to predict an orbit one day into the future, you have to integrate an 48-hour orbit arc and fit it to the 24-hour orbit arc of the current day. Unfortunately we don't have any config files available for this task, so you will have to create one yourself. You can try using the script `020groopsGnssPreprocessing.xml` in the `scenarioGnssNetwork` scenario mentioned above as a starting point. You will have adapt it from 24-hour arcs to 48-hour arcs. If you then use a 24-hour arc as a reference orbit (inputfileOrbit) for the fit in PreprocessingVariationalEquationOrbitFit, this should achieve what you want to do. I've never done this myself so I can't help you further with this.

**Comment by FFFFFG-IGG** [comment]
> Hello,
> 
> Release [2021-09-06](https://github.com/groops-devs/groops/releases/tag/2021-09-06) features a redesign of the GNSS processing interface to make usage a little bit easier and more flexible. In addition, we now provide GNSS [example scenarios](https://ftp.tugraz.at/outgoing/ITSG/groops/scenario/) with config files and data. Since the structure of the [GNSS-related GROOPS data and metadata](https://ftp.tugraz.at/outgoing/ITSG/groops/data/gnss/) has changed, we recommend to download the latest version. More information can be found in the updated [cookbooks and documentation](https://groops-devs.github.io/groops/html/index.html).
> 
> If you want to predict an orbit one day into the future, you have to integrate an 48-hour orbit arc and fit it to the 24-hour orbit arc of the current day. Unfortunately we don't have any config files available for this task, so you will have to create one yourself. You can try using the script `020groopsGnssPreprocessing.xml` in the `scenarioGnssNetwork` scenario mentioned above as a starting point. You will have adapt it from 24-hour arcs to 48-hour arcs. If you then use a 24-hour arc as a reference orbit (inputfileOrbit) for the fit in PreprocessingVariationalEquationOrbitFit, this should achieve what you want to do. I've never done this myself so I can't help you further with this.

I have solved all my problems through reading source code, lol. It's very exciting news that the update of GROOPS has been uploaded. Now I'm going to take a deep look in it, many thanks!
