### ISSUE TITLE
Warning: unknown variables

### ISSUE THREAD

**Issue by FFFFFG-IGG** [groops-devs/groops#18]
Hello developers, when I get start in the new version of the groop(2021-09-06), I meet some bugs and have difficulty solving them.
some details are in the following fig:
![image](https://user-images.githubusercontent.com/59271400/132358637-2f1d1ec3-0f1f-4701-85e4-67c07e8a37ff.png)
![image](https://user-images.githubusercontent.com/59271400/132358690-2adc33b4-9db5-4b52-ba59-d0fd0f048403.png)
These bugs did not appear in the last version, and I'm looking forward to your suggestion! many thanks!

**Comment by sestras** [comment]
This is not a bug. These warnings let you know that your config file contains elements that GROOPS cannot interpret because they are not defined in the version you are using. In this case, these warnings appear because in those programs the interface has changed and these elements are not defined anymore or have a different name.

From the second screenshot, I assume that you are trying to run one of the example scenarios? Since the new config elements (transmitter GNSS etc.) are not read properly, it seems like you are running the new scripts with an old version of GROOPS. Please make sure you recompile GROOPS after updating to the latest release and confirm that you are running the newly compiled GROOPS executable. You can check by calling the executable without any arguments (e.g. just groops or groops.exe in Windows). At the bottom of the help text it says (Compiled: xxx).
