### ISSUE TITLE
Compile and run Groops by docker?

### ISSUE THREAD

**Issue by amour2049** [groops-devs/groops#21]
Hello Torsten、Sebastian and Andreas , I am an engineer engaged in GNSS data processing. Thank you for developing a great software.The Groops software has a clear architecture and uses many features of a modern language. I like it very much.
In the process of installation and using, I found that Groops still has some inconveniences. Mainly on compiling and building the Groops software,the steps of running the ring build and compiling are a bit complicated. You need to  install libexpat1-dev, libopenblas-dev and other dependencies when compiling.In addition, the installation of these environments may also affect the original development environment. 
Therefore, I thought of using docker to solve this problem.Using docker can perfectly solve the problem of compilation and operation without affecting the environment of the existing system. At present, I have compiled and built an image with docker, and it is very convenient to use. I will continue to improve my dockfile and related compilation and usage scripts and documents in the future.And i will submit these changes to github, will you accept this PR? Thank you!   @tmayerguerr @sestras @akvas

**Comment by akvas** [comment]
Dear @amour2049,

this is an interesting proposition and certainly worth looking into, thanks! Baking the GROOPS installation into a Dockerfile would indeed be a good alternative for people who already have Docker/podman already setup on their machines. 

The crucial point in the design of the image would be the interaction between the container and host filesystem, since GROOPS relies on input files possibly from and to a variety of locations on the host.  For a generic enough Dockerfile, I see no way around specifying volumes/mounts on the command line which could make using the image somewhat tedious. 

I suggest that you commit/post your Dockerfile as a starting point for a discussion and see if and how we can integrate it.

Cheers,
Andreas

**Comment by akvas** [comment]
Hi amour2049,

thanks for providing your Dockerfile! I have come up with something similar, but found that this is not easy to generalize. Specifically, one hast to extensively work with mounts if the project is more complex and requires multiple data sources.

We have discussed publishing GROOPS via container and found that at the moment we are not able support this feature. We are however happy to revisit this issue if community demand picks up.

Thanks again and cheers,
Andreas
