### ISSUE TITLE
How to pass variable created by GnssPrn2SvnBlockVariable to PreprocessingVariationalEquation

### ISSUE THREAD

**Issue by different91988** [groops-devs/groops#3]
Hi, I try to follow the cookbook to process GNSS observation with PPP technique, however I cannot find a proper way to save the svn and block varibale generated by GnssPrn2SvnBlockVariable and pass to other program like PreprocessingVariationEquation. It seems only global varibal predefined in config file can be shared between program.  How to solve this issue?

**Comment by sestras** [comment]
Hi, GnssPrn2SvnBlockVariables creates variables for SVN and block that can be used in all subsequent programs on the same level or below. So if PreprocessingVariationalEquation comes after GnssPrn2SvnBlockVariables, you can use {svn} in a config element, for example inputfileSatelliteModel, and it will be replaced by the SVN. I've attached a small example config file that shows how to use it.

[example.zip](https://github.com/groops-devs/groops/files/5649370/example.zip)

**Comment by sestras** [comment]
Hi Frank,

I'm glad it works. There's definitely room for improvement in the documentation/cookbook examples to make them clearer and easier to understand. If you have any suggestions, feel free to open an issue or pull request. And yes, we plan to provide some example config files for the cookbook.

Sebastian

**Comment by sestras** [comment]
Hello, in case you are still interested, we now have some example scenarios available, including one for PPP:

Release [2021-09-06](https://github.com/groops-devs/groops/releases/tag/2021-09-06) features a redesign of the GNSS processing interface to make usage a little bit easier and more flexible. In addition, we now provide GNSS [example scenarios](https://ftp.tugraz.at/outgoing/ITSG/groops/scenario/) with config files and data. Since the structure of the [GNSS-related GROOPS data and metadata](https://ftp.tugraz.at/outgoing/ITSG/groops/data/gnss/) has changed, we recommend to download the latest version. More information can be found in the updated [cookbooks and documentation](https://groops-devs.github.io/groops/html/index.html).

**Comment by different91988** [comment]
Hi Sebastian,

Thanks for your work! I think this example scenario will be a good start point to read and work with groops.
