### ISSUE TITLE
Daily timeseries with uncertainties - follow up

### ISSUE THREAD

**Issue by Bemtgenj** [groops-devs/groops#38]
Hallo Patrick, Hallo Sebastian,
 I have a follow up question with regards to the xml program (with the 2 options) you have sent to Parisa.
I ran both options separately and got the following results - for option 2 the date started "shifting" a few times of the *.5 number. I did not have that all for option 1. Both programs use the same input data. I have looked through the file and have not yet come up with an explanation for the drift. Parisa only ran option1 and her dates align with my option 1. As both options use the same input data i had assumed the results would be the same (although the approach is different between the two)

 I will further investigate today to see if i can find where this is coming from. Did you ever come across this kind of difference?  I have included the files as well as that might help with the understanding of the question

Option 1 – Jan 01 – Nov 29          finished stat1_op1_pos&cov.txt               Date              58849.5 -> 59182.5 ok
Option 1 – Dec 2 – Dec 31           finished stat2_op1_pos&cov.txt               Date              59185.5 -> 59214.5 ok

Option2 – Jan 01 – Nov29            finished 1_statistics_op2.txt                      Date              58849.5 -> 59007.5, 59008.135, 59008.644, 5900.5 -> 59812.5
Option 2 – Dec 01 – Dec 31         finished2_statistics_op2.txr                      Date:              59185.5 -> 59196.5, 59197.0012, 59197.0069, 59197.0021, 59197.515, 59198.5 -> 59214.5
Note: we had to split the time series into 2 sets as there is no data available for Nov 30 and Dec 1

Thanks for the help
MfG
Jean

[groops.zip](https://github.com/groops-devs/groops/files/8302112/groops.zip)

**Comment by zhedumi** [comment]
Hi Jean,

As far as I can tell there is no timeshift or drift within the calculations. In the second option after you have merged the data you are synchronizing them with [InstrumentSynchronize](https://groops-devs.github.io/groops/html/InstrumentSynchronize.html). [InstrumentSynchronize](https://groops-devs.github.io/groops/html/InstrumentSynchronize.html) will split the data into the given daily timeseries arcs. Furthermore, since **minGap** is not set, it will further split the arcs due to data gaps > 1.5median sampling as noted within the documentation and description.

 So what happens in your case is that that the day 59008 (8.6.2020) has a data gap resulting in two arcs for that day. To create one arc per day neglecting data gaps just set **minGap** = 0.

In my example script within https://github.com/groops-devs/groops/issues/36 I just neglected that data gaps can occur. 

Best Regards,

Patrick

As a sidenote you can also comment in closed issues which can help in grouping same issues for future references.

**Comment by Bemtgenj** [comment]
Hi Patrick,

Txs for the explanation, that helps a lot. We are still learning all the details of GROOPS .

Good suggestion We will do that in the future.

BR
Jean
