### ISSUE TITLE
Expression To Compute Colour For a Residual SkyPlot

### ISSUE THREAD

**Issue by Galatiy** [groops-devs/groops#39]
Greetings Patrick,

I am reaching out regarding the PlotMapLayerPoints function. I am interested in superimposing the residuals on the satellite trajectories. However, I am not sure how to impose a condition to link the color bar and the residuals values. In the point layer, I tried to define ‘if(X, n, NAN)’ where X is the data column and n is a number, but I still obtained the trajectories clustered at the center of the SkyPlot. 

For the sake of clarity, here is my script:
[plotResidualSkyplot.zip](https://github.com/groops-devs/groops/files/8304389/plotResidualSkyplot.zip)

I tested with the '' residuals_2020-01-02.graz.dat" and here is the sample data:

[residuals_2020-01-02.graz.dat.zip](https://github.com/groops-devs/groops/files/8304380/residuals_2020-01-02.graz.dat.zip)
[residualData.zip](https://github.com/groops-devs/groops/files/8304388/residualData.zip)

Note: I deliberately left the ‘min’ and ‘max’ combo boxes (for the color bar definition) empty to enable automatic capture of its extents. 

I, therefore, wonder if you could advise in this matter. 

Thanks for your understanding and support.

Galatiya.

**Comment by sestras** [comment]
Hi Galatiya,

I think that there are several misunderstandings with respect to the settings in your script. If I understand correctly, you want to visualize the residuals from the receiver's perspective (i.e., in the form of a skyplot).

Here is what I changed in your script to achieve this:
1. Removed A and E types in GnssResiduals2Skyplot. Azimuth and elevation are already encoded in the "longitude" and "latitude" of the output grid (see [documentation](https://groops-devs.github.io/groops/html/GnssResiduals2Skyplot.html))
2. Removed typeTransmitter in GnssResiduals2Skyplot. As stated in the [documentation](https://groops-devs.github.io/groops/html/GnssResiduals2Skyplot.html), if you select a transmitter with this option, the residuals are plotted from the satellite's point of view, which is why you ended up with all data being clustered in the center of the skyplot. 
3. In PlotMap-layer-points, changed value to data0*100 . data0 corresponds to the first type set in GnssResiduals2Skyplot and *100 to convert it to cm, since you used that in the colorbar unit (unit is just text, you have to convert manually to what you want). I'm not sure what you were trying to achieve with the if statement, but it is not necessary.
4. Removed lines between points as they don't make sense in this plot.
5. Changed R and inverseFlattening to 1 and 0 in GnssResiduals2Skyplot to be consistent with the settings in PlotMap (again as stated in the [documentation](https://groops-devs.github.io/groops/html/GnssResiduals2Skyplot.html)).

With these changes, I got the following plot, which is what I assume you want:
![ResidualSkyPlot](https://user-images.githubusercontent.com/9025982/159014624-ac4ee183-7924-43b1-bee8-beec483b5c98.png)

Here's the updated script:
[plotResidualSkyplot.xml.zip](https://github.com/groops-devs/groops/files/8304936/plotResidualSkyplot.xml.zip)

Please make sure to carefully read the documentation of the programs and their config elements to avoid any confusion and incorrect settings.

Best regards,
Sebastian

**Comment by Galatiy** [comment]
Hi Sebastian,

Many thanks for your assistance. 

I acknowledge receipt of the updated script, and I will carefully make use of the GROOPS documentation as advised. 

Thanks for your usual support.

Regards,

Galatiya.
