### ISSUE TITLE
about instrument_detrend.cpp

### ISSUE THREAD

**Issue by zdwangjian5** [groops-devs/groops#40]
Hi, I meet a problem again. The execution result of the "detrend" function in matlab software and the execution result of instrument_detrend.cpp are found to be very different. Can you help to look into this? Thank you!

**Comment by akvas** [comment]
Hi @zdwangjian5,

small differences are expected because MATLAB uses [ordinary least squares](https://www.mathworks.com/help/matlab/ref/detrend.html), while GROOPS uses [robust least squares](https://groops-devs.github.io/groops/html/fundamentals.robustLeastSquares.html) as stated in the [documentation](https://groops-devs.github.io/groops/html/InstrumentDetrend.html). Please consider consulting the documentation of [programs](https://groops-devs.github.io/groops/html/programType.html) and [classes](https://groops-devs.github.io/groops/html/classes.html) before opening an issue.

Cheers,
Andreas

**Comment by zdwangjian5** [comment]
But not small difference. very different.



---Original---
From: "Andreas ***@***.***&gt;
Date: Tue, Mar 22, 2022 18:22 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [groops-devs/groops] about instrument_detrend.cpp (Issue #40)




 
Hi @zdwangjian5,
 
small differences are expected because MATLAB uses ordinary least squares, while GROOPS uses robust least squares as stated in the documentation. Please consider consulting the documentation of programs and classes before opening an issue.
 
Cheers,
 Andreas

**Comment by zdwangjian5** [comment]
@akvas 
![differences](https://user-images.githubusercontent.com/101688056/159617162-d1d9788b-4b31-4e20-b9d7-72f02ecea8eb.PNG)
Please take a look at this data and its output using detrend in matlab and instrument_detrend.cpp.Not small differences.

**Comment by sestras** [comment]
Hello,

First of all, the file you attached is not a valid GROOPS file (InstrumentType -23 is not defined). From that I assume that you somehow created this file outside of GROOPS. In any case, after removing the header, I was able to process the file with InstrumentDetrend using parametrizationTemporal _constant_ and _trend_. The result is as expected and to me looks identical to your figure of the Matlab output.

![detrend](https://user-images.githubusercontent.com/9025982/159885197-69dda056-1a76-4807-af17-e49f0370c8cd.png)

Therefore, I don't see how this is a GROOPS issue. Since you did not provide any information on what your settings are (i.e., the GROOPS config file), I cannot tell you what the issue on your end might be.

Best regards,
Sebastian

**Comment by zdwangjian5** [comment]
Thank you for your help. This is my settings.
![image](https://user-images.githubusercontent.com/101688056/160032060-596cce27-52c4-4ce0-9c18-f1743192ee45.png)
