### ISSUE TITLE
About Instrument2RmsPlotGrid

### ISSUE THREAD

**Issue by gnssxx** [groops-devs/groops#44]
### Description

Hello，
I want to draw a picture of the long track RMS. Can you provide an example of XML file configuration for Instrument2RmsPlotGrid? Thank you!

regards，
J

### GROOPS version

Release 2021-09-06

### Operating systems

- [ ] Linux
- [X] Windows
- [ ] macOS
- [ ] Other (please specify in the description)

**Comment by tmayerguerr** [comment]
Hello J,

Unfortunately, I can't help you because you don't provide enough information. What are you planning to do? What topic are you talking about (GNSS orbit determination, LEO kinematic orbits, GRACE gravity field recovery, space weather applications, ...)?
From what kind of data do you want to compute the RMS? Maybe you are looking at the wrong program? To transform the data into the satellite frame (along, cross, radial) you can use InstrumentRotate. Use InstrumentSynchronize to divide the orbits into arcs. To analyze the data and compute some statistics, maybe the programs InstrumentArcStatistics or InstrumentArcCalculate are the better choice. 

regards
Torsten

**Comment by gnssxx** [comment]
Hello，
Sorry, the problem is not described clearly.
What I want to ask is about the determination of GNSS orbit. I want to compare the GPS orbit with the final IGS final solution through the Instrument2RMSPlotGrid program, and create a-month-long RMS grid from the daily GPS orbit files (like the picture below). but I am not clear about the XML file configuration and related calculations, so I can't get the desired results. So I want to ask about the XML file configuration scheme, which programs are used, and what is the calculation order.
![tmp2AA0](https://user-images.githubusercontent.com/75126376/163774943-ab0b818b-bbeb-4275-bcf4-63c7f000c8b5.png)

**Comment by tmayerguerr** [comment]
ah, okay. You can adapt the attached config [groopsOrbitRmsTimeSeries.zip](https://github.com/groops-devs/groops/files/8504434/groopsOrbitRmsTimeSeries.zip) (see settings in the global section). The script plots also the time series of Helmert parameters (translation, rotation, scale)

**Comment by gnssxx** [comment]
I'd be most grateful for your help. Thanks a lot.
